Map<String, String> arLocale = {
  // intro
  'logo': 'نجومي',
  'boarding1_title': 'كل نجمة تصنع فرقًا',
  'boarding1_info':
      'في Starry، يمكنك دعم الحملات الإنسانية\nباستخدام النجوم بدل المبالغ المالية.',

  'boarding2_title': 'تبرّع بطريقة أبسط',
  'boarding2_info':
      'اختر عدد النجوم، تبرّع بسهولة،\n وتابع أثر مساهمتك خطوة بخطوة.',

  'boarding3_title': 'ابدأ فورًا بدون تعقيد',
  'boarding3_info':
      'يمكنك التبرّع مباشرة دون إنشاء حساب،\n أو إنشاء حساب لمتابعة تأثيرك بشكل كامل.',

  'skip': 'تخطي',
  'start_now': 'ابدأ الآن',
  'welcome_title': ' كل نجمة تصنع فرقًا',
  'welcome_subtitle':
      'تبرّع بالنجوم لدعم الحملات الإنسانية ومتابعة أثر تبرعك بكل شفافية',
  'donate_now': 'تبرّع الآن',
  'welcome_extra': 'يمكنك التبرّع مباشرة دون إنشاء حساب',
  'sign_in_up': 'تسجيل الدخول / إنشاء حساب',
  'create_ur_acc': ' أنشئ حسابك في Starry ✨',
  'create_acc_info': 'أنشئ حسابك للبدء في دعم الحملات أو إنشاء حملتك الخاصة.',
  'first_name': 'الاسم الأول',
  'last_name': 'الاسم الأخير',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'create_acc': 'إنشاء الحساب',
  'have_acc': 'لديك حساب بالفعل ؟ تسجيل الدخول',
  'or': 'أو',
  'login_with_google': 'المتابعة باستخدام Google',
  'login_with_apple': 'المتابعة باستخدام Apple',
  'by_continue': '🔒 بياناتك محمية ولا تتم مشاركة أي معلومات بدون إذنك.',
  'welcome_back': 'مرحبا بعودتك ✨',
  'sign_in_info':
      'أدخل بياناتك للوصول إلى حملاتك وتبرعاتك، ومتابعة الأثر الذي تصنعه نجومك ⭐',
  'login': 'تسجيل الدخول',
  'forgot_password': 'نسيت كلمة المرور؟',
  'dont_have_acc': 'ليس لديك حساب ؟ إنشاء حساب جديد ',
  'frgt_pswd_title': 'نسيت كلمة المرور؟ لا تقلق ✨',
  'frgt_pswd_info':
      'أدخل بريدك الإلكتروني المسجّل لدينا، وسنرسل لك رابطًا آمنًا لإعادة تعيين كلمة المرور.',
  'reset_password': 'إرسال رابط إعادة التعيين',
  'enter_verification': 'أدخل رمز التحقق',
  'verification_info':
      'أرسلنا رمز تحقق مكوّن من 5 أرقام إلى بريدك الإلكتروني. الرجاء إدخال الرمز لإكمال العملية.',
  'sent_to': 'تم الإرسال إلى  ',
  'confirm_code': 'تأكيد الرمز',
  'didnt_recieve_code': 'لم يصلك الرمز؟ إعادة الإرسال ',
  'after': 'بعد ',
  'second': 'ثانية',
  'code_availability': '🔒الرمز صالح لفترة محدودة.',
  'assign_new_pass': '🔑 تعيين كلمة مرور جديدة',
  'assign_new_pass_info': 'اختر كلمة مرور قوية لحماية حسابك',
  'new_password': 'كلمة المرور الجديدة',
  'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
  'first_rule': ' 8 أحرف على الأقل',
  'second_rule': ' تحتوي على رقم',
  'third_rule': 'تحتوي على رمز خاص',
  'fourth_rule': 'كلمتا المرور متطابقتان',
  'update_password': 'تحديث كلمة المرور',
  'go_to_login': 'الانتقال إلى تسجيل الدخول',
  'login_safely': 'يمكنك الاّن تسجيل الدخول بأمان',
  'password_changed': '✅ تم تحديث كلمة المرور بنجاح',
  'every_star_makes_a_difference': 'كل نجمة تصنع فرقًا',
  'title_campaigns_list': 'حملة ضمن تعليم',
  'how_to_use': 'كيف ترغب باستخدام Starry؟',
  'how_to_use_info': 'اختر الطريقة التي تناسبك، يمكنك تغييرها لاحقًا',
  'donator': 'متبرع',
  'donator_extra': 'دعم الحملات، التبرع بالنجوم، ومتابعة الأثر',
  'creator': 'منشئ حملة',
  'creator_extra': 'إنشاء حملات، جمع التبرعات، وإدارة الأرباح',
  'continue': 'استمرار',
  'welcome_creator': '✨ أهلاً بك كمنشئ حملة في Starry',
  'welcome_creator_info':
      'هنا يمكنك إنشاء حملات، جمع التبرعات، وتتبع الأثر الحقيقي لكل نجمة تصل إليك.',
  'welcome_donator': '✨ أهلاً بك كمتبرع في Starry',
  'welcome_donator_info':
      'هنا يمكنك دعم الحملات الإنسانية باستخدام النجوم، ومتابعة الأثر الحقيقي لتبرعاتك.',
  'start_setting_up': 'ابدأ الإعداد',
  'what_account_type': 'ما نوع الحساب الذي ترغب بإنشائه؟',
  'choose_ur_best': 'اختر الخيار الأنسب لك، يمكنك التعديل لاحقًا',
  'individual': 'فردي',
  'individual_info': 'إنشاء حملات شخصية أو إنسانية بشكل مستقل.',
  'organization': 'مؤسسة / منظمة',
  'organization_info': 'تمثيل جهة رسمية أو منظمة غير ربحية.',
  'team': 'فريق / مبادرة',
  'team_info': 'العمل كفريق أو مبادرة مجتمعية.',
  'step': 'خطوة',
  'of': 'من',
  'next': 'متابعة',
  'what_campaign_types': 'ما نوع الحملات التي تخطط لإنشائها؟',
  'select_one_or_more': 'اختر نوعًا واحدًا أو أكثر، لمساعدتنا في تخصيص تجربتك.',
  'water': 'مياه',
  'food_relief': 'إغاثة غذائية',
  'education': 'تعليم',
  'health': 'صحة',
  'shelter': 'إيواء',
  'animals': 'حيوانات',
  'environment': 'بيئة',
  'what_experience_level': 'ما مدى خبرتك في إنشاء الحملات؟',
  'experience_screen_info': 'يساعدنا هذا في تقديم تجربة تناسبك.',
  'first_time': ' هذه أول مرة ',
  'first_time_info': 'أحتاج ارشاداً خطوة بخطوة',
  'someExperience': 'لدي خبرة سابقة',
  'someExperience_info': 'انشأت حملات من قبل',
  'expert': 'لدي خبرة واسعة',
  'expert_info': 'أدير حملا بشكل احترافي',
  'basic_trust_info': 'معلومات أساسية للثقة',
  'trust_info_extra': 'تساعد هذه المعلومات في بناء الثقة مع الداعمين.',
  'visible_name': 'الاسم الظاهر للحساب',
  'name_or_company': 'اسمك أو اسم الجهة',
  'city_country': 'الدولة / المدينة',
  'city_country_example': 'مثال : غزة - فلسطين',
  'company_name': 'اسم الجهة أو المبادرة',
  'company_name_example': 'مثال: جمعية الأمل الخيرية',
  'company_url': 'رابط الموقع أو حساب اجتماعي',
  'company_url_example': 'https://...........',
  'save_and_continue': 'حفظ والمتابعة',
  'setup_success': 'تم إعداد حسابك بنجاح 🎉',
  'ready_to_go': 'أصبحت جاهزًا لإطلاق حملتك الأولى وجمع النجوم بكل وضوح وثقة.',
  'create_first_campaign': 'إنشاء اول حملة',
  'discover_dashboard': 'استكشاف لوحة التحكم',
  'payment_method': 'أختر طريقة الدفع',
  'Card_payment': 'الدفع بالبطاقة',
  'Confirmation_of_donation': 'تأكيد التبرّع',
  'Thank_you!': 'شكراً لك !',
  'Donation_Summary': 'ملخص التبرّع',
  'Card_information': 'معلومات البطاقة',
  'Card_number': 'رقم البطاقة',
  'Expiry_date': 'تاريخ الانتهاء',
  'Security_code': 'رمز الأمان',
  'Cardholder_name': 'اسم حامل البطاقة',
  'As_shown_on_the_card': 'كما يظهر على البطاقة',
  'bank_card': 'بطاقة بنكية ',
  'Donation_details': 'تفاصيل التبرّع',
  'Number_of stars': 'عدد النجوم',
  'Donation_value': 'قيمة التبرع',
  'Service_fees': 'رسوم الخدمة',
  'Total_donation_amount': 'إجمالي مبلغ التبرع',
  'Payment_tracking': 'متابعة الدفع',
  'Donation_completed': 'إتمام التبرع',
  'All_card_data_is_protected_and_encrypted.':
      'جميع بيانات البطاقة محمية ومشفرة',
  'All_payments_are_secure_and_encrypted.': 'جميع عمليات الدفع آمنة ومشفرة',
  'The_payment_process_is_secure_and_fully encrypted.':
      'عملية الدفع آمنة و مشفرة بالكامل',
  'Confirmation_of_donation_amount': 'تأكيد مبلغ التبرع',
  'Explore_other_campaigns': 'استكشاف حملات أخرى',
  'Create_an_account_to_track_your_progress': 'إنشاء حساب لتتبع أثرك',
  'Shakel': 'شيكل',
  'Your_donation': 'تبرعك بـ',
  'Donation_impact_description': 'يساهم في توفير مياه نظيفة للأسر المحتاجة.',
  'Campaign_title_sample': 'قطرة حياة: مياه نظيفة لأطفال غزة',
  'details_info': 'المعلومات الشخصية',
  'how_many_stars': '⭐كم نجمة تود أن تهدي؟',
  'safe_and secure_donation': 'تبرع امن ومضمون',
  'account_settings': 'إعدادات الحساب',
  'manage_your_account_here': 'تدير بياناتك وأمان حسابك من هنا',
  'security_and_privacy': 'الأمان والخصوصية',
  'notification_preferences': 'تفضيلات الاشعارات',
  'donation_record': 'سجل التبرعات',
  'account_verification': 'توثيق الحساب',
  'bank_account_management': 'إدارة الحساب البنكي',
  'wallet': 'المحفظة',
  'help _and_support': 'المساعدة والدعم',
  'logout': 'تسجيل الخروج',
  'delete_account': 'حذف الحساب',
  'my_campaigns': 'حملاتي',
  'manage_campaigns_and_track': 'هنا يمكنك إدارة جميع حملاتك وتتبع تقدمها',
  'progress_achieved': 'التقدم المنجز',
  'edit_campaign': 'تعديل الحملة',
  'campaign_management': 'إدارة الحملة',
  'add_update': 'اضف تحديث',
  'delete_campagin': 'حذف الحملة',
  'stop_compagin': 'ايقاف الحملة',
  'repost_the_campaign': 'اعادة نشرالحملة',
  'resume_the campaign': 'استئناف الحملة ',

  'what_account_to_verify': 'ما نوع الحساب الذي ترغب بتوثيقه؟',
  'what_account_to_verify_info': 'حدد نوع الحساب الذي يمثل نشاطك بشكل أفضل',
  'id_info': 'معلومات الهوية الشخصية',
  'id_info_extra':
      'التأكّد من أن الحساب يعود لشخص حقيقي بدون الدخول في تعقيد قانوني.',
  'full_name_label': 'الاسم الكامل (كما في الهوية)',
  'id': 'رقم الهوية',
  'id_type': 'نوع الهوية',
  'personal_id': 'هوية شخصية',
  'passport': 'جواز سفر',
  'id_pic': 'صورة الهوية',
  'front_id': 'إضافة صورة الوجه الأمامي من الهوية شخصية',
  'please_add_clear_img': 'يرجى ارفاق صور واضحة ',
  'back_id': 'إضافة صورة الوجه الخلفي من الهوية شخصية',
  'personal_pic': 'صورة شخصية',
  'take_pic': 'اضغط للتصوير',
  'take_pic_info': 'يرجى اخذ صورة واضحة لك وانت تحمل الهوية',
  'transactions_info': 'بيانات التحويل البمكي',
  'disclaimer':
      'التأكّد من أنمعلومات البنك يعود لشخص حقيقي بدون الدخول في تعقيد قانوني.',
  'bank_acc_holder_name': 'اسم صاحب الحساب',
  'checked_by_id': 'تم التحقق من الاسم عبر الهوية الوطنية',
  'iban_label': 'رقم الايبان (IBAN)',
  'iban_hint': '  **** **** **** **** ***pal',
  'iban_check': 'تأكد من ادخال 24 رقم بعد رمز الدولة pal',
  'bank_name': 'اسم البنك ',
  'bank_of_palestine': 'بنك فلسطين',
  'donations_transactions_routines':
      'يتم تحويل التبرعات اسبوعيا الى هذا الحساب بشكل آلي وامن , وتخضع جميع البيانات لمعايير التشفير البنكي.',
  'send_to_verify': 'إرسال الطلب للمراجعة',
  'confirmation_recieved': 'تم استلام وثائق التوثيق بنجاح.',
  'information_will_be_reviewed':
      'سيقوم فريق Starry بمراجعتها خلال 24–48 ساعة.',
  'review_extra':
      'نقوم بمراجعة المعلومات  للتأكد من وضوح الهدف ومصداقية المحتوى قبل نشرها.',
  'review_duration': 'تستغرق المراجعة عادة من 24 إلى 48 ساعة.',
  'msg_will_be_rec': 'ستصلك رسالة إشعار فور توثيق حسابك',
  'discover_campains': 'استكشاف الحملات',
  'contact_support': 'تواصل مع الدعم الفني',
  'start_verifying': 'ابدأ توثيق حسابك',
  'donor_verifying_letter':
      'خطوات بسيطة تساعدنا في تعزيز الثقة داخل المنصة وحماية جميع المستخدمين.',
  'no_third_parties': 'لن نشارك معلوماتك مع أي طرف ثالث.',
  'why_verfiying_important': 'لماذا التوثيق مهم',
  'blue_icon': 'شارة التوثيق الزرقاء',
  'special_icon': 'علامة مميزة تظهر بجانب اسمك',
  'extra_protection': 'حماية إضافية للحساب',
  'layers_of_protection': 'طبقات أمان متقدمة لحسابك',
  'support_priority': 'أولوية في الدعم الفني',
  'special_support': 'فريق دعم متخصص للمساعدة في حل مشاكلك',
  'start_verfication': 'ابدأ التوثيق',
  'send_code': ' إرسال رمز التحقق',
  'confirm_email': 'تأكيد البريد الإلكتروني',
  'how_email_is_used': 'نستخدم بريدك فقط لتأكيد هويتك.',
  'confirm_code_and_continue': 'تأكيد الرمز و متابعة',
  'confirm_mobile': 'تأكيد رقم الهاتف',
  'how_phone_is_used': 'يساعدنا رقم الهاتف في حماية حسابك.',
  'phone': 'رقم الهاتف',
  'send_sms': 'رسالة نصية',
  'send_whatsapp': 'رسالة واتساب',
  'dob': 'تاريخ الميلاد',
  'country': 'الدولة',
  'add_id': 'إضافة صورة الهوية شخصية',
  'add_clear_id': 'يرجى ارفاق صور واضحة للهوية الشخصية',
  'send_to_revision': 'مراجعة وإرسال',
  'identity': 'الهوية',
  'mobile': 'الهاتف',
  'mail': 'البريد',
  'information_rec': 'تم استلام معلوماتك بنجاح.',
  'go_to_dash': 'الانتقال إلى لوحة التحكم',
  'clear_summary': 'ملخص واضح',
  'personal_info': 'المعلومات الشخصية',
  'personal_picture': 'الصورة الشخصية',
  'change_profile_picture': 'تغيير صورة الملف الشخصي',
  'save_changes': 'حفظ التغييرات',
  'city': 'المدينة',
  'campaign_title': 'عنوان الحملة',
  'campaign_type': 'نوع الحملة',
  'campaign_title_hint': 'مثال: مياه نظيفة للعائلات المحتاجة',
  'description': 'وصف مختصر للحملة',
  'description_hint': 'اكتب وصفًا قصيرًا يوضح هدف الحملة وتأثيرها',
  'campaign_info': 'معلومات الحملة الأساسية',
  'campaign_define': 'ابدأ بتعريف حملتك، يمكنك تعديل التفاصيل لاحقًا.',
  'cancel': "الغاء",
  'step_of': 'خطوة @current من @total',
  'The number of stars is used to measure progress,\n not as a monetary amount':
      ' يُستخدم عدد النجوم لقياس التقدم وليس كمبلغ مالي',
  'campaign_aim': 'هدف الحملة (عدد النجوم)',
  'campaign_aim_hint': 'مثال: 5,000 نجمة',
  'campaign_photo': 'صورة الحملة',
  'add_campaign_image': 'إضافة صورة للحملة',
  'campaign_image_hint': 'يفضل صورة واضحة و بسيطة تعبر عن هدف الحملة.',
  'image_optional': 'يمكنك إضافة الصورة لاحقا',
  'This description is shown to donors and helps them make\n a decision.':
      'هذا الوصف يظهر للمتبرعين ويساعدهم في اتخاذ القرار.',
  'under_review': 'حملتك قيد المراجعة الآن ',
  'thank_you_for_your_submission':
      'شكرًا لك! تم إرسال حملتك لمراجعتها من قبل فريق Starry.',
  'go_to_dashboard': 'الانتقال إلى لوحة التحكم',
  'display_campaign_details': 'عرض تفاصيل الحملة',
  'review_info1':
      'نقوم بمراجعة الحملات للتأكد من وضوح الهدف ومصداقية المحتوى قبل نشرها',
  'review_info2': 'تستغرق المراجعة عادة من 24 إلى 48 ساعة.',
  'aim_details': ' تفاصيل الهدف والتقدّم',
  'aim_interval': 'حدّد مدة حملتك وكيف سيتم تتبّع التقدّم بالنجوم.',
  'campaign_interval': 'مدة الحملة',
  'campaign_endDate': 'تاريخ انتهاء الحملة',
  'extend_duration': 'يمكنك تمديد المدة لاحقًا إذا لزم الأمر.',
  'continue_process': 'كيف يتم تتبّع التقدّم؟',
  'progress': 'يتم قياس تقدّم الحملة بناءً على عدد النجوم التي يتم جمعها.',
  'vendor_message': 'رسالة التقدّم للداعمين',
  'vendor_message_hint': 'مثال: كل 100 نجمة تقرّبنا خطوة من هدفنا',
  'This message appears below the progress bar.':
      'تظهر هذه الرسالة أسفل شريط التقدّم.',
  'optional': 'اختياري',
  'campaign_rev': 'مراجعة الحملة قبل النشر',
  'check_details': 'تأكّد من صحة التفاصيل قبل نشر حملتك. يمكنك التعديل لاحقًا.',

  'send_campaign': 'إرسال الحملة للمراجعة',
  'save_campaign': 'حفظ كمسودة',
  "campaign_name": 'اسم الحملة',
  "campaign_name_value": 'دعم تعليم الأطفال المحتاجين',
  "description_value":
      'تبرّع بالنجوم لدعم الحملات الإنسانية ومتابعة أثر تبرعك بكل شفافية.',
  "alert":
      'ستظهر هذه المعلومات للمتبرعين كما هي , يرجى التأكد من خلوها من الأخطاء الإملائية.',
  "confirm":
      ' أؤكد أن المعلومات المقدّمة صحيحة، وأن الحملة تهدف لأثر إنساني حقيقي..',
  "donation_history": "سجل التبرعات",
  'donation_history_description':
      " هنا يمكنك الاطلاع على جميع التبرعات التي قمت بها وتتبع أثرها.",
  'supported_campaigns': '@count الحملات المدعومة ',
  'no_donations_yet': "لا توجد تبرعات بعد",
  'start_campaign': "ابدأ بدعم حملة لإحداث أثر",
  'donation_list': "قائمة التبرعات",
  'view_campaign': "عرض الحملة",
  'explore_campaigns': "استكشف حملات جديدة",
  "notifications_title": "الاشعارات",
  "mark_all_read": "تحديد كمقروء",
  "notifications_subtitle": "آخر التحديثات المتعلّقة بأثرك داخل المنصة",
  "no_notifications_yet": 'لا توجد إشعارات بعد',
  "new_label": 'الجديدة',
  "yesterday_label": 'الأمس',
  'notification_settings': "تفضيلات الإشعارات",
  'notification_settings_subtitle':
      "اختر ما تحب أن يصلك من تحديثات وأخبار الأثر",
  'impact_notification': "إشعارات الأثر",
  'contribution_notification': "إشعارات الحملات",
  'security_notification': "إشعارات النظام",
  'donation_updates': "تحديثات أثر تبرعاتك",
  'donation_updates_desc':
      "تلقى إشعارات عندما يتحقق أثر حقيقي لتبرعك أو تظهر نتائج جديدة.",
  'campaign_progress': "تقدم الحملات التي دعمتها",
  'campaign_progress_desc':
      "تلقى إشعارات عند وصول الحملة إلى مراحل مهمة أو اقترابها من تحقيق هدفها.",
  'new_campaigns_interests': "حملات جديدة تناسب اهتماماتك",
  'new_campaigns_interests_desc':
      "إشعار عن حملات قريبة من المجالات التي تهمك في حال رغبت بذلك.",
  'closing_campaigns': "حملات قريبة من الاكتمال",
  'closing_campaigns_desc':
      "إشعار عند اقتراب حملة من تحقيق هدفها لتكون جزءاً من لحظاتها الأخيرة.",
  'security_notifications': "إشعارات النظام",
  'account_security_alerts': "تنبيهات الحساب والأمان",
  'account_security_alerts_desc':
      '"إشعارات مهمة متعلقة بتسجيل الدخول أو تغييرات الأمان في حسابك."',
  'account_updates': "تحديثات الحساب",
  'accouunt_updates_desc':
      "نخبرك بأي تحديثات ضرورية متعلقة بحسابك أو إعداداته.",
  'verification_account': 'توثيق الحساب',
  'verification_account_description':
      'يساعد التوثيق في تعزيز ثقة الآخرين بتفاعلك داخل المنصة.',
  'account_verified': 'حسابك موثق',
  'account_verified_descriton': 'حسابك موثّق ويمكنك الاستفادة من جميع ميزات المنصة بثقة.',
  'verification_pending': 'حسابك قيد المراجعة',
  'verification_time': 'تاريخ التوثيق',
  'ability_reverification':'يمكنك تحديث المعلومات المطلوبة وإعادة إرسال طلب التوثيق.',
  'account_under_review': 'تم استلام معلوماتك وجارٍ مراجعتها.',
  'expected_time': 'الوقت المتوقع',
  'expected_time_description': 'عادة خلال 24–48 ساعة',
  'verified_account_benefits': 'ما الذي يتيحه الحساب الموثق ؟',
  'notification_when_verified':
      'سيتم إشعارك فور توثيق حسابك أو في حال فشل التوثيق',
  'retry_verification': 'إعادة المحاولة',
  'contact_wit_support': 'التواصل مع الدعم',
  'security_privacy_settings': 'تتحكم هنا بأمان حسابك وخصوصية بياناتك',
  'account_security': 'أمان الحساب',
  'change_password': 'تغيير كلمة المرور',
  'login_activity': 'نشاط تسجيل الدخول',
  'two_factor_authentication': 'المصادقة الثنائية',
  'two_factor_authentication_description':
      'قم بتأمين حسابك باستخدام رمز إضافي عند تسجيل الدخول لزيادة مستوى الحماية',
  'update_password_description':
      'تحديث كلمة المرور بشكل دوري يساعد في حماية حسابك من الاختراقات المحتملة',
  'required': 'مطلوب',
  'email_required': 'يرجى ادخال البريد الالكتروني',
  'invalid_email': 'يرجى ادخال بريد الكتروني صالح',
  'password_required': 'كلمة المرور مطلوبة',
  'password_too_short': 'كلمة المرور اقل من 8 خانات',
  'passwords_not_match': 'كلمة المرور غير متطابقة',
  'verification_failed': 'تعذّر توثيق الحساب',
  'verification_failed_description':
      'لم نتمكن من توثيق حسابك في الوقت الحالي بسبب نقص أو عدم وضوح بعض المعلومات.',
  'verification_failed_reason': 'سبب عدم التوثيق',
  'payment_way': 'طرق الدفع',
  'Here_you_can_track_your_impact_and_support_new_campaigns_with_stars':
      'هنا يمكنك متابعة أثرك ودعم حملات جديدة بالنجوم',
  'Your_current_impact': 'أثرك الحالي',
  'You_are_in_the_top_%_of_star_donors!':
      'أنت من بين أعلى @peploepresnt٪ من المتبرعين هذا الشهر',
  'Life_affected': 'حياة تأثرت',
  'Sponsored_campaigns': 'حملات مدعومة',
  'Latest_donations': 'آخر التبرعات',
  'Campaign_Offer': 'عرض الحملة',
  'Explore_new_campaigns': 'استكشف حملات جديدة',
  'Suggested_campaigns_for_you': 'حملات مقترحة لك',
  'View_details': 'مشاهدة التفاصيل',
  'Relief': 'إغاثي',
  'Every_star_contributes_to_making_a_real_difference':
      'كل نجمة تساهم في إحداث فرق حقيقي',
  'Goal': 'الهدف : @Number نجمة',
  'Donate_immediately': 'تبرع فوراً',
  'Active_now': 'نشط الآن',
  'Offline': 'غير متصل',
  'Login_activity': 'نشاط تسجيل الدخول',
  'Here_you_can_see_the_latest_logins_to_your_account.':
      'هنا يمكنك الاطلاع على آخر عمليات تسجيل الدخول إلى حسابك.',
  'We_monitor_your_account_activity_to_ensure_your_security._You_can_review_your_connected_devices_below.':
      'نحن نراقب نشاط حسابك للتأكد من أمانك يمكنك مراجعة الأجهزة المتصلة أدناه',
  'Current_session': 'الجلسة الحالية',
  'Other_sessions': 'جلسات أخرى',
  'Starry_app_for': 'تطبيق Starry لنظام @OSName',
  'End_session': 'إنهاء الجلسة',
  'Logout_form_All_Devices': 'تسجيل الخروج من كل الأجهزة',
  'Here_you_can_track_Your_donation_balance_and_manage_the_impact_transfer_with_complete_transparency.':
      'هنا يمكنك متابعة رصيد التبرعات وإدارة تحويل\n الأثر بكل شفافية.',
  'Available_balance': 'الرصيد المتاح',
  'Withdrawal pending processing': 'سحب قيد المعالجة : @amount  شيكل',
  'Request_to_withdraw_profits': 'طلب سحب الأرباح',
  'Transfer_log': 'سجل التحويلات',
  'Number_of_stars_you_want_to_convert': 'عدد النجوم التي تريد تحويلها',
  'Another_number...': 'رقم آخر...',
  'bank_account': 'الحساب البنكي',
  'The_stars_you_want_to_pull': 'النجوم التي تريد سحبها',
  'Platform_fees': 'رسوم المنصة',
  'Star_value': 'قيمة النجمة',
  'Net_number_of_stars': 'عدد النجوم الصافي',
  'net_amount': 'المبلغ الصافي',
  'Confirm_withdrawal_request': 'تأكيد طلب السحب',
  'Confirmation_of_profit_withdrawal': 'تأكيد سحب الأرباح',
  'Your_withdrawal_request_has_been_received_successfully!':
      'تم استلام طلب السحب بنجاح!',
  'Your_request_will_be_reviewed_and_the_payment_will_be_sent_to_your_bank_Saccount.':
      'سيتم مراجعة طلبك وارسال المبلغ الى حسابك البنكي',
  'Expected_arrival_time': 'وقت الوصول المتوقع',
  'The_review_usually_takes_24_to_48_hours.':
      'تستغرق المراجعة عادة من 24 إلى 48 ساعة.',
  'Go_to_the_control_panel': 'الانتقال إلى لوحة التحكم',
  'Return_to_wallet': 'العودة للمحفظة',
  'Campaign_Management': 'إدارة الحملة',
  'Control_the_details_of_your_campaign_and_monitor_its_performance.':
      'تحكم في تفاصيل حملتك وتابع أداءها',
  "It_ends_within_days": "تنتهي خلال @days يوم",
  'Dayes': 'يوم',
  'Add_Update': 'إضافة تحديث',
  'Share': 'مشاركة',
  'Edit': 'تعديل',
  'Performance_Overview': 'نظرة عامة على الأداء',
  'Total_stars_collected': 'إجمالي النجوم المجمعة',
  'Supporters': 'الداعمين',
  'Days_remaining': 'أيام متبقية',
  'Latest_updates': 'آخر التحديثات',
  'View_all': 'عرض الكل',
  'Campaign_temporarily_suspended': 'ايقاف الحملة مؤقتاً',
  'Delete_the_campaign_permanently': 'حذف الحملة نهائياً',
  'star': 'نجمة',
  'Active': 'نشطة',
  'Add_campaign_update': 'إضافة تحديث للحملة',
  'Keep_donors_informed_about_your_campaign_update_and_progress.':
      'أطلع المتبرعين على تحديثات حملتك وانجاز تقدمها',
  'Complete_campaign': 'حملة مكتملة',
  'Example:Thank_you_for_your_support': 'مثال: شكرا لدعمكم',
  'Update_content': 'محتوى التحديث',
  'Write_a_short_description_that_explains_the_goal_of_the_campaign_update.':
      'اكتب وصفًا قصيرًا يوضح هدف تحديث الحملة',
  'Add_a_photo_or_video_(optional)': 'أضف صورة أو مقطع فيديو (اختياري)',
  'Click_to_download': 'انقر للتحميل',
  'Post the update': 'نشر التحديث',
  'Update_Title': 'عنوان التحديث',
  'Edit_campaign_details': 'تعديل تفاصيل الحملة ',
  'Control_the_details_of_your_campaign': 'تحكم في تفاصيل حملتك',
  'Campaign_title': 'عنوان الحملة',
  'Brief_description_of_the_campaign': 'وصف مختصر للحملة',
  'Campaign_type': 'نوع  الحملة',
  'Campaign_duration': 'مدة الحملة',
  'Campaign_objective': 'هدف الحملة',
  'motivational_message': 'رسالة تحفيزية ',
  'Media': 'الوسائط',
  'Save_changes': 'حفظ التعديلات',
  'Changes_saved': 'تم حفظ التعديلات',
  'Choose_media_type': 'اختر نوع الملف',
  'Photo': 'صورة',
  'Video': 'فيديو',
  'Only_mp4_allowed': 'يرجى اختيار فيديو بصيغة MP4',
  'Only_images_allowed': 'يرجى اختيار صورة بصيغة JPG أو PNG',
  'Field_required': 'هذا الحقل مطلوب',
  'Invalid_number': 'يرجى إدخال رقم صحيح',
  'Fill_required_fields': 'يرجى تعبئة الحقول المطلوبة',
  'Unsupported_format': 'صيغة الملف غير مدعومة',
  'Add_thumbnail': 'إضافة صورة مصغّرة؟',
  'Add_thumbnail_question': 'هل تريد رفع صورة مصغّرة مخصصة للفيديو؟',
  'Choose_thumbnail': 'اختيار',
  'Skip': 'تخطي',
  'Payment_methods': 'طرق الدفع',
  'Choose_the_most_convenient_way_to_buy_stars_and_donate_easily.':
      'اختر الطريقة الأنسب لشراء النجوم والتبرع بسهوله',
  'Saved_cards': 'البطاقات المحفوظة',
  'hypothetical': 'افتراضي',
  'It_ends_in': ' تنتهي في @date',
  'Add_a_new_card': 'اضافة بطاقة جديدة',
  'Fast_payment': 'دفع سريع',
  'Apple_pay': 'Apple pay',
  'paypal': 'paypal',
  'Save_card': 'حفظ البطاقة',
  'bank_accounts': 'الحسابات البنكية',
  'Verified': 'متحقق',
  'current_pass': 'كلمة المرور الحالية',
  'paused': 'موقوفة مؤقتاً',
  'draft': 'مسودة',
  'deleted': 'محذوفة',
  'institution_name': 'اسم المؤسسة الرسمي',
  'institution_example': 'مثال : جمعية الأمل الخيرية',
  'license_number': 'رقم الترخيص / السجل',
  'license_example': '1010xXXXX',
  'foundation_date': 'تاريخ التأسيس',
  'required_files': 'الوثائق المطلوبة ',
  'license_certificate': 'شهادة التسجيل او الرخصة',
  'manager_id': 'هوية المفوض (مدير الحساب)',
  'add_license': 'ارفق شهادة التسجيل أو الرخصة',
  'only_front_id': ' صورة الوجه الأمامي من الهوية شخصية فقط',
  'authorization_letter': 'خطاب التفويض',
  'add_authorization_letter': 'ارفق خطاب التفويض الرسمي للمؤسسة',
  'manager_personal_pic': 'صورة شخصية للمفوض',
  'only_bank_account':
      'يجب أن يكون الحساب البنكي باسم المؤسسة فقط لن يتم قبول الحسابات الشخصية',
  'institution_acc': 'اسم صاحب الحساب ( مطابق للرخصة )',
  'institution_iban': 'رقم الايبان (IBAN) للمؤسسة',
  '': '',
  'pending' : 'قيد المراجعة', 
  'completed' : 'مكتملة', 
  'stopped' : 'موقوفة',
  'campaign' : 'حملة',
  "title_delete_campaign": "حذف الحملة",
  "msg_delete_campaign": "هل أنت متأكد أنك تريد حذف هذه الحملة؟",
  "btn_cancel": "إلغاء",
  "btn_delete": "حذف",
  "success_delete_campaign": "تم حذف الحملة بنجاح",
  "error_delete_campaign": "فشل حذف الحملة"

};
