Map<String, String> enLocale = {
  // intro
  'logo': '',
  'boarding1_title': '',
  'boarding2_title': '',
  'boarding1_info': '',
  'boarding2_info': '',
  'next': 'Next',
  'start_now': 'Start Now',
  'sign_in': 'Sign In',

  'Edit': 'Edit',
  'Share': 'Share',
  'Add_Update': 'Add update',
  'Active': 'Active',
  'It_ends_within_days': 'Ends within @days days',
  'star': 'star',
  'Edit_campaign_details': 'Edit campaign details',
  'Control_the_details_of_your_campaign':
      'Control the details of your campaign',
  'Campaign_title': 'Campaign title',
  'Brief_description_of_the_campaign': 'Brief description of the campaign',
  'Campaign_type': 'Campaign type',
  'Campaign_duration': 'Campaign duration',
  'Campaign_objective': 'Campaign objective',
  'motivational_message': 'Motivational message',
  'Media': 'Media',
  'Save_changes': 'Save changes',
  'Changes_saved': 'Changes saved',
  'Choose_media_type': 'Choose media type',
  'Photo': 'Photo',
  'Video': 'Video',
  'Only_mp4_allowed': 'Please select an MP4 video',
  'Only_images_allowed': 'Please select a JPG or PNG image',
  'Field_required': 'This field is required',
  'Invalid_number': 'Please enter a valid number',
  'Fill_required_fields': 'Please fill the required fields',
  'Unsupported_format': 'Unsupported file format',
  'Add_thumbnail': 'Add thumbnail?',
  'Add_thumbnail_question': 'Do you want to upload a custom thumbnail?',
  'Choose_thumbnail': 'Choose',
  'Skip': 'Skip',
  'Latest_donations': 'Latest donations',
  'Campaign_Offer': 'Campaign offer',
  'Explore_new_campaigns': 'Explore new campaigns',
  'Suggested_campaigns_for_you': 'Suggested campaigns for you',
  'View_details': 'View details',
  'donate_now': 'Donate now',
  'Goal': 'Goal: @Number stars',

  'campaign_title': 'Campaign Title',
  'campaign_type': 'Campaign Type',
  'campaign_title_hint': 'Example: Clean Water for Families in Need',
  'description': 'Brief Description of the Campaign',
  'description_hint':
      'Write a short description that explains the campaign goal and its impact',
  'campaign_info': 'Basic Campaign Information',
  'campaign_define':
      'Start by defining your campaign, you can modify the details later.',
  'cancel': 'Cancle',
  'step_of': 'Step @current of @total',
  'campaign_aim': 'Campaign Aim (Number of Stars)',
  'campaign_aim_hint': 'Example: 5,000 Stars',
  'campaign_photo': 'Campaign Photo',
  'add_campaign_image': 'Add Campaign Image',
  'campaign_image_hint':
      'Upload an image that represents your campaign. This will help attract more supporters.',
  'image_optional': 'Image is Optional',
  'under_review': 'Your Campaign is Under Review',
  'thank_you_for_your_submission':
      'Thank you for submitting your campaign. Our team is currently reviewing it to ensure it meets our guidelines. You will be notified once the review is complete.',
  'go_to_dashboard': 'Go to Dashboard',
  'display_campaign_details': 'Display Campaign Details',
  'review_info1':
      'Review campaigns to ensure the clarity of their goals and the credibility of their content before publishing',
  'review_info2':
      'The review process typically takes up to 48 hours. We appreciate your patience during this time.',
  'aim_details': 'Aim Details',
  'aim_interval':
      'Define the specific objectives and milestones for your campaign to help track progress and engage supporters.',
  'campaign_interval': 'Campaign Interval',
  'campaign_endDate': 'Campaign End Date',
  'extend_duration': 'You can extend the duration later if needed.',
  'continue_process': 'You can continue the process.',
  'progress':
      'The campaign’s progress is measured based on the number of stars collected.',
  'vendor_message': 'Message for Vendors ',
  'vendor_message_hint': 'write your message for vendors here',
  'campaign_rev': 'Campain Review',
  'check_details':
      'Confirm the details before publishing your campaign. You can edit them later.',

  'send_campaign': 'Send the campaign for review',
  'save_campaign': 'Save as draft',
  'campaign_name': 'Campaign Name',
  'campaign_name_value': 'Supporting the education of children in need',
  'description_value':
      'Donate stars to support humanitarian campaigns and track the impact of your donation with complete transparency.',
  'alert':
      'This information will appear to donors as is, please make sure it is free of spelling errors.',
  'confirm':
      'I confirm that the information provided is correct and that the campaign aims for a real humanitarian impact.',
  'donation_history': 'Donation History',
  'donation_history_description':
      'Here you can view all the donations you have made and track their impact.',
  'supported_campaigns': 'Supported Campaigns: @count',
  'no_donations_yet': 'No donations yet',
  'start_campaign': 'Start supporting a campaign to make an impact',
  'donation_list': 'Donation List',
  'view_campaign': 'View Campaign',
  'explore_campaigns': 'Explore New Campaigns',
  'notifications_title': 'Notifications',
  'mark_all_read': 'Mark all as read',
  'notifications_subtitle':
      'Latest updates related to your impact within the platform',
  'no_notifications_yet': 'No notifications yet',
  'new_label': 'New',
  'yesterday_label': 'Yesterday',
  'notification_settings': 'Notification Settings',
  'notification_settings_subtitle':
      'Choose what you would like to receive from updates and news from Al Athar.',
  'impact_notification': 'Impact Notifications',
  'contribution_notification': 'Contribution Notifications',
  'security_notification': 'Security Notifications',
  'donation_updates': 'Updates on the Impact of Your Donations',
  'donation_updates_desc':
      'Receive notifications when a real impact from your donation is made or new results appear.',
  'campaign_progress': 'The campaigns that were supported',
  'campaign_progress_desc':
      'Receive notifications when the campaign reaches important milestones or is close to achieving its goal.',
  'new_campaigns_interests': 'New campaigns that match your interests',
  'new_campaigns_interests_desc':
      'Notification about campaigns related to the fields that interest you, if you wish.',
  'closing_campaigns': 'Campaigns close to completion',
  'closing_campaigns_desc':
      'A notification when a campaign is about to reach its goal, to be part of its final moments.',
  'security_notifications': 'Security Notifications',
  'account_security_alerts': 'Account and Security Alerts',
  'account_security_alerts_desc':
      'Important notifications related to login or security changes on your account.',
  'account_updates': 'Account Updates',
  'accouunt_updates_desc':
      'We will inform you of any necessary updates related to your account or its settings.',

  // Added missing keys
  'Active_now': 'Active now',
  'Add_a_new_card': 'Add a new card',
  'Add_a_photo_or_video_(optional)': 'Add a photo or video (optional)',
  'Add_campaign_update': 'Add campaign update',
  'All_card_data_is_protected_and_encrypted.': 'All card data is protected and encrypted.',
  'All_payments_are_secure_and_encrypted.': 'All payments are secure and encrypted.',
  'Another_number...': 'Another number...',
  'Apple_pay': 'Apple pay',
  'As_shown_on_the_card': 'As shown on the card',
  'Available_balance': 'Available balance',
  'Campaign_Management': 'Campaign Management',
  'Campaign_temporarily_suspended': 'Campaign temporarily suspended',
  'Campaign_title_sample': 'Campaign title sample',
  'Card_information': 'Card information',
  'Card_number': 'Card number',
  'Card_payment': 'Card payment',
  'Cardholder_name': 'Cardholder name',
  'Choose_the_most_convenient_way_to_buy_stars_and_donate_easily.': 'Choose the most convenient way to buy stars and donate easily.',
  'Click_to_download': 'Click to download',
  'Complete_campaign': 'Complete campaign',
  'Confirm_withdrawal_request': 'Confirm withdrawal request',
  'Confirmation_of_donation': 'Confirmation of donation',
  'Confirmation_of_donation_amount': 'Confirmation of donation amount',
  'Confirmation_of_profit_withdrawal': 'Confirmation of profit withdrawal',
  'Control_the_details_of_your_campaign_and_monitor_its_performance.': 'Control the details of your campaign and monitor its performance.',
  'Create_an_account_to_track_your_progress': 'Create an account to track your progress',
  'Current_session': 'Current session',
  'Dayes': 'Days',
  'Days_remaining': 'Days remaining',
  'Donate_immediately': 'Donate immediately',
  'Donation_Summary': 'Donation Summary',
  'Donation_details': 'Donation details',
  'Donation_impact_description': 'Donation impact description',
  'Donation_value': 'Donation value',
  'End_session': 'End session',
  'Every_star_contributes_to_making_a_real_difference': 'Every star contributes to making a real difference',
  'Example:Thank_you_for_your_support': 'Example:Thank you for your support',
  'Expected_arrival_time': 'Expected arrival time',
  'Expiry_date': 'Expiry date',
  'Explore_other_campaigns': 'Explore other campaigns',
  'Fast_payment': 'Fast payment',
  'Go_to_the_control_panel': 'Go to the control panel',
  'Here_you_can_see_the_latest_logins_to_your_account.': 'Here you can see the latest logins to your account.',
  'Here_you_can_track_Your_donation_balance_and_manage_the_impact_transfer_with_complete_transparency.': 'Here you can track your donation balance and manage impact transfers with complete transparency.',
  'Here_you_can_track_your_impact_and_support_new_campaigns_with_stars': 'Here you can track your impact and support new campaigns with stars.',
  'It_ends_in': 'It ends in',
  'Keep_donors_informed_about_your_campaign_update_and_progress.': 'Keep donors informed about your campaign updates and progress.',
  'Latest_updates': 'Latest updates',
  'Life_affected': 'Life affected',
  'Login_activity': 'Login activity',
  'Logout_form_All_Devices': 'Logout form All Devices',
  'Net_number_of_stars': 'Net number of stars',
  'Number_of stars': 'Number of stars',
  'Number_of_stars_you_want_to_convert': 'Number of stars you want to convert',
  'Offline': 'Offline',
  'Other_sessions': 'Other sessions',
  'Payment_methods': 'Payment methods',
  'Payment_tracking': 'Payment tracking',
  'Performance_Overview': 'Performance Overview',
  'Platform_fees': 'Platform fees',
  'Post the update': 'Post the update',
  'Request_to_withdraw_profits': 'Request to withdraw profits',
  'Return_to_wallet': 'Return to wallet',
  'bank_transfer': 'Bank transfer',
  'school_bag_campaign_donation': 'School bag campaign donation',
  'wallet_sample_date': '2025/Oct/25',
  'commercial_bank': 'Commercial Bank',
  'after_two_days': 'After two days',
  'Save_card': 'Save card',
  'Saved_cards': 'Saved cards',
  'Security_code': 'Security code',
  'Service_fees': 'Service fees',
  'Shakel': 'Shekel',
  'Sponsored_campaigns': 'Sponsored campaigns',
  'Star_value': 'Star value',
  'Starry_app_for': 'Starry app for',
  'Supporters': 'Supporters',
  'Thank_you!': 'Thank you!',
  'The number of stars is used to measure progress,\n not as a monetary amount': 'The number of stars is used to measure progress,\nnot as a monetary amount.',
  'The_payment_process_is_secure_and_fully encrypted.': 'The payment process is secure and fully encrypted.',
  'The_review_usually_takes_24_to_48_hours.': 'The review usually takes 24 to 48 hours.',
  'This description is shown to donors and helps them make\n a decision.': 'This description is shown to donors and helps them make\na decision.',
  'This message appears below the progress bar.': 'This message appears below the progress bar.',
  'Total_donation_amount': 'Total donation amount',
  'Total_stars_collected': 'Total stars collected',
  'Transfer_log': 'Transfer log',
  'Update_Title': 'Update Title',
  'Update_content': 'Update content',
  'Update_published': 'Update published',
  'Verified': 'Verified',
  'View_all': 'View all',
  'We_monitor_your_account_activity_to_ensure_your_security._You_can_review_your_connected_devices_below.': 'We monitor your account activity to keep you secure. You can review your connected devices below.',
  'Withdrawal pending processing': 'Withdrawal pending processing',
  'Write_a_short_description_that_explains_the_goal_of_the_campaign_update.': 'Write a short description that explains the goal of the campaign update.',
  'You_are_in_the_top_%_of_star_donors!': 'You are in the top % of star donors!',
  'Your_current_impact': 'Your current impact',
  'Your_donation': 'Your donation',
  'Your_request_will_be_reviewed_and_the_payment_will_be_sent_to_your_bank_Saccount.': 'Your request will be reviewed and the payment will be sent to your bank account.',
  'Your_withdrawal_request_has_been_received_successfully!': 'Your withdrawal request has been received successfully!',
  'account_security': 'Account security',
  'account_settings': 'Account settings',
  'account_verification': 'Account verification',
  'active': 'Active',
  'add_clear_id': 'Add clear ID',
  'add_id': 'Add ID',
  'add_update': 'Add update',
  'after': 'After',
  'animals': 'Animals',
  'assign_new_pass': 'Assign new pass',
  'assign_new_pass_info': 'Assign new pass info',
  'back_id': 'Back ID',
  'bank_acc_holder_name': 'Bank acc holder name',
  'bank_account': 'Bank account',
  'bank_account_management': 'Bank account management',
  'bank_accounts': 'Bank accounts',
  'bank_card': 'Bank card',
  'bank_of_palestine': 'Bank of palestine',
  'basic_trust_info': 'Basic trust info',
  'blue_icon': 'Blue icon',
  'boarding3_info': 'Start right away with no complexity, and set up your account in minutes.',
  'boarding3_title': 'Boarding3 title',
  'by_continue': 'By continue',
  'campaign_management': 'Campaign management',
  'campaign_review_note_1': 'We review campaigns to ensure clear goals and credible content before publishing.',
  'campaign_review_note_2': 'The review usually takes up to @hours hours.',
  'campaign_under_review_desc': 'Your campaign has been sent for review and you will be notified when it is complete.',
  'campaign_under_review_title': 'Your campaign is under review',
  'change_password': 'Change password',
  'change_profile_picture': 'Change profile picture',
  'checked_by_id': 'Checked by ID',
  'choose_ur_best': 'Choose ur best',
  'city': 'City',
  'clear_summary': 'Clear summary',
  'code_availability': 'Code availability',
  'company_name': 'Company name',
  'company_name_example': 'Company name example',
  'company_url': 'Company URL',
  'company_url_example': 'Company URL example',
  'completed': 'Completed',
  'confirm_code': 'Confirm code',
  'confirm_code_and_continue': 'Confirm code and continue',
  'confirm_email': 'Confirm email',
  'confirm_mobile': 'Confirm mobile',
  'confirm_new_password': 'Confirm new password',
  'confirmation_recieved': 'Confirmation recieved',
  'contact_support': 'Contact support',
  'contact_wit_support': 'Contact wit support',
  'continue': 'Continue',
  'country': 'Country',
  'create_acc': 'Create acc',
  'create_acc_info': 'Create acc info',
  'create_first_campaign': 'Create first campaign',
  'create_ur_acc': 'Create ur acc',
  'creator': 'Creator',
  'creator_extra': 'Creator extra',
  'delete_account': 'Delete account',
  'delete_campagin': 'Delete campaign',
  'deleted': 'Deleted',
  'details_info': 'Details info',
  'didnt_recieve_code': 'Didnt recieve code',
  'disclaimer': 'Disclaimer',
  'discover_campains': 'Discover campains',
  'discover_dashboard': 'Discover dashboard',
  'dob': 'Dob',
  'donation_record': 'Donation record',
  'donations_transactions_routines': 'Donations are transferred to your account in scheduled cycles.',
  'donator': 'Donator',
  'donator_extra': 'Donator extra',
  'donor_verifying_letter': 'Verification helps protect the community and build trust.',
  'dont_have_acc': 'Dont have acc',
  'draft': 'Draft',
  'edit_campaign': 'Edit campaign',
  'education': 'Education',
  'email': 'Email',
  'email_required': 'Email required',
  'enter_verification': 'Enter verification',
  'environment': 'Environment',
  'error': 'Error',
  'every_star_makes_a_difference': 'Every star makes a difference',
  'expected_time': 'Expected time',
  'expected_time_description': 'Expected time description',
  'experience_screen_info': 'Experience screen info',
  'expert': 'Expert',
  'expert_info': 'Expert info',
  'extra_protection': 'Extra protection',
  'first_name': 'First name',
  'first_rule': 'First rule',
  'first_time': 'First time',
  'first_time_info': 'First time info',
  'food_relief': 'Food relief',
  'forgot_password': 'Forgot password',
  'fourth_rule': 'Fourth rule',
  'frgt_pswd_info': 'Enter your email and we will send you a reset link.',
  'frgt_pswd_title': 'Frgt pswd title',
  'front_id': 'Front ID',
  'full_name_label': 'Full name label',
  'go_to_dash': 'Go to dash',
  'go_to_login': 'Go to login',
  'have_acc': 'Have acc',
  'health': 'Health',
  'help _and_support': 'Help and support',
  'how_email_is_used': 'How email is used',
  'how_many_stars': 'How many stars',
  'how_phone_is_used': 'How phone is used',
  'how_to_use': 'How to use',
  'how_to_use_info': 'How to use info',
  'hypothetical': 'Hypothetical',
  'iban_check': 'IBAN check',
  'iban_hint': 'IBAN hint',
  'iban_label': 'IBAN label',
  'id': 'ID',
  'id_info': 'ID info',
  'id_info_extra': 'Your ID information is used only for verification and will not be shared.',
  'id_pic': 'ID pic',
  'identity': 'Identity',
  'individual': 'Individual',
  'individual_info': 'Individual info',
  'information_rec': 'Information rec',
  'information_will_be_reviewed': 'Your information will be reviewed.',
  'invalid_email': 'Invalid email',
  'last_name': 'Last name',
  'layers_of_protection': 'Layers of protection',
  'login': 'Login',
  'login_activity': 'Login activity',
  'login_safely': 'Login safely',
  'login_with_apple': 'Login with apple',
  'login_with_google': 'Login with google',
  'logout': 'Logout',
  'mail': 'Mail',
  'manage_campaigns_and_track': 'Manage campaigns and track',
  'manage_your_account_here': 'Manage your account here',
  'mobile': 'Mobile',
  'msg_will_be_rec': 'Msg will be rec',
  'my_campaigns': 'My campaigns',
  'name_or_company': 'Name or company',
  'net_amount': 'Net amount',
  'new_password': 'New password',
  'no_third_parties': 'No third parties',
  'notification_preferences': 'Notification preferences',
  'notification_when_verified': 'You will be notified once your account is verified.',
  'of': 'Of',
  'optional': 'Optional',
  'or': 'Or',
  'organization': 'Organization',
  'organization_info': 'Organization info',
  'passport': 'Passport',
  'password': 'Password',
  'password_changed': 'Password changed',
  'password_required': 'Password required',
  'password_too_short': 'Password too short',
  'passwords_not_match': 'Passwords not match',
  'paused': 'Paused',
  'payment_method': 'Payment method',
  'paypal': 'Paypal',
  'personal_id': 'Personal ID',
  'personal_info': 'Personal info',
  'personal_pic': 'Personal pic',
  'personal_picture': 'Personal picture',
  'phone': 'Phone',
  'please_add_clear_img': 'Please add clear img',
  'progress_achieved': 'Progress achieved',
  'ready_to_go': 'Ready to go',
  'repost_the_campaign': 'Repost the campaign',
  'required': 'Required',
  'reset_password': 'Reset password',
  'resume_the campaign': 'Resume the campaign',
  'retry_verification': 'Retry verification',
  'review_duration': 'Review duration',
  'review_extra': 'Your data is protected and used only for verification.',
  'safe_and secure_donation': 'Safe and secure donation',
  'save_and_continue': 'Save and continue',
  'save_changes': 'Save changes',
  'second': 'Second',
  'second_rule': 'Second rule',
  'security_and_privacy': 'Security and privacy',
  'security_privacy_settings': 'Security privacy settings',
  'select_campaign_type': 'Please select a campaign type.',
  'select_one_or_more': 'Select one or more',
  'send_code': 'Send code',
  'send_sms': 'Send sms',
  'send_to_revision': 'Send to revision',
  'send_to_verify': 'Send to verify',
  'send_whatsapp': 'Send whatsapp',
  'sent_to': 'Sent to',
  'setup_success': 'Setup success',
  'shelter': 'Shelter',
  'sign_in_info': 'Sign in to continue to your account.',
  'sign_in_up': 'Sign in up',
  'sign_out': 'Sign out',
  'skip': 'Skip',
  'someExperience': 'Some Experience',
  'someExperience_info': 'Some Experience info',
  'special_icon': 'Special icon',
  'special_support': 'Special support',
  'start_setting_up': 'Start setting up',
  'start_verfication': 'Start verification',
  'start_verifying': 'Start verifying',
  'step': 'Step',
  'stop_compagin': 'Stop campaign',
  'stopped': 'Stopped',
  'support_priority': 'Support priority',
  'take_pic': 'Take pic',
  'take_pic_info': 'Take pic info',
  'team': 'Team',
  'team_info': 'Team info',
  'third_rule': 'Third rule',
  'title_campaigns_list': 'Title campaigns list',
  'transactions_info': 'Transactions info',
  'trust_info_extra': 'Trust info extra',
  'two_factor_authentication': 'Two factor authentication',
  'two_factor_authentication_description': 'Two factor authentication description',
  'update_password': 'Update password',
  'update_password_description': 'Update password description',
  'verification_account': 'Verification account',
  'verification_account_description': 'Verify your account to unlock benefits and increase trust.',
  'verification_failed': 'Verification failed',
  'verification_failed_description': 'Verification failed description',
  'verification_info': 'Enter the verification code we sent you.',
  'verified_account_benefits': 'Verified account benefits',
  'visible_name': 'Visible name',
  'wallet': 'Wallet',
  'water': 'Water',
  'welcome_back': 'Welcome back',
  'welcome_creator': 'Welcome creator',
  'welcome_creator_info': 'You can create campaigns, collect stars, and manage your earnings.',
  'welcome_donator': 'Welcome donator',
  'welcome_donator_info': 'You can support campaigns, donate stars, and track impact.',
  'welcome_extra': 'Welcome extra',
  'welcome_subtitle': 'Donate easily and make a real difference.',
  'welcome_title': 'Welcome title',
  'what_account_to_verify': 'What account to verify',
  'what_account_to_verify_info': 'What account to verify info',
  'what_account_type': 'What account type',
  'what_campaign_types': 'What campaign types',
  'what_experience_level': 'What experience level',
  'why_verfiying_important': 'Why verifying important',

  // '': '',
};
