Map<String, String> enLocale = {
  // intro
  'logo': '',
  'boarding1_title': '',
  'boarding2_title': '',
  'boarding1_info': '',
  'boarding2_info': '',
  'next': 'Next',
  'start_now': 'Start Now',
  'sign_in': 'Sign In',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
};
