Map<String, String> enLocale = {
  // intro
  'logo': '',
  'boarding1_title': '',
  'boarding2_title': '',
  'boarding1_info': '',
  'boarding2_info': '',
  'next': 'Next',
  'start_now': 'Start Now',
  'sign_in': 'Sign In',
  'Edit': 'Edit',
  'Share': 'Share',
  'Add_Update': 'Add update',
  'Active': 'Active',
  'It_ends_within_days': 'Ends within @days days',
  'star': 'star',
  'Edit_campaign_details': 'Edit campaign details',
  'Control_the_details_of_your_campaign':
      'Control the details of your campaign',
  'Campaign_title': 'Campaign title',
  'Brief_description_of_the_campaign': 'Brief description of the campaign',
  'Campaign_type': 'Campaign type',
  'Campaign_duration': 'Campaign duration',
  'Campaign_objective': 'Campaign objective',
  'motivational_message': 'Motivational message',
  'Media': 'Media',
  'Save_changes': 'Save changes',
  'Changes_saved': 'Changes saved',
  'Choose_media_type': 'Choose media type',
  'Photo': 'Photo',
  'Video': 'Video',
  'Only_mp4_allowed': 'Please select an MP4 video',
  'Only_images_allowed': 'Please select a JPG or PNG image',
  'Field_required': 'This field is required',
  'Invalid_number': 'Please enter a valid number',
  'Fill_required_fields': 'Please fill the required fields',
  'Unsupported_format': 'Unsupported file format',
  'Add_thumbnail': 'Add thumbnail?',
  'Add_thumbnail_question': 'Do you want to upload a custom thumbnail?',
  'Choose_thumbnail': 'Choose',
  'Skip': 'Skip',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
  // '': '',
};
